# Generated by Django 3.0.4 on 2021-06-04 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resturant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('direction', models.CharField(max_length=200, unique=True)),
                ('hyper_link', models.CharField(max_length=500, unique=True)),
                ('hours_open', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(max_length=200, unique=True)),
            ],
        ),
    ]
